[project]
name = "bookworm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "orjson>=3.10.18",
    "tqdm>=4.67.1",
]
